language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

before_script:
  - composer --dev install

script:
  - vendor/bin/phpunit
  - vendor/bin/phpcs --standard=PSR1,PSR2 --ignore=vendor,cache,Behaviors .
